### ISSUE TITLE
I need a little help~

### ISSUE THREAD

**Issue by Cralykie** [Ruuv1337/projectile#3]
I want to try this code but I'm not play in  the RU server , would u mind to update this code counter the TW server if this don't cost u a lot of time?I can pay for this . Thx~

**Comment by Xiatu** [comment]
Пользуясь открытым вопросом, спрошу. Можно ли ссылку на готовый, запакованный zip-Proxy с опкодами на слеш. Ибо я не особо понял как все фискить. RU-Регион.  Если будет время, и желание. Спасибо

**Comment by Ruuv1337** [comment]
``Share opc only for RU region.``
Гайд по настройке\установке прокси найдете здесь: https://meishuu.github.io/tera-proxy/
И здесь: https://teraproxy.tumblr.com/
