### ISSUE TITLE
Unrecognized Hook

### ISSUE THREAD

**Issue by glenn88** [Ruuv1337/projectile#4]
I get

[dispatch] hook: unrecognized hook target S_END_USER_PROJECTILE<1>
[dispatch] hook: unrecognized hook target C_HIT_USER_PROJECTILE<2>

Does not work on EU version. Do I need to change something?

**Comment by jamesluca** [comment]
I get

[dispatch] hook: unrecognized hook target S_END_USER_PROJECTILE<1>
[dispatch] hook: unrecognized hook target C_HIT_USER_PROJECTILE<2>

Does not work on NA version. Do I need to change something?

**Comment by Ruuv1337** [comment]
Are you sure that you put the *.def* files in the folder you want?
