### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jamesluca** [Ruuv1337/projectile#5]
I get

[dispatch] hook: unrecognized hook target S_END_USER_PROJECTILE<1>
[dispatch] hook: unrecognized hook target C_HIT_USER_PROJECTILE<2>

Does not work on NA version. Do I need to change something?

**Comment by Ruuv1337** [comment]
Are you sure that you put the *.def* files in the folder you want?

**Comment by jamesluca** [comment]
yes i put def files in folder protocol

**Comment by jamesluca** [comment]
you can put the folder with the proxy installed, because I've done everything and this error persists?

**Comment by Ruuv1337** [comment]
You do not have an opcode for you region.
Find it.
